/**
 * Two Thumbs — roster, power-ups, constants
 * Six wizards · Six defenders · MIT
 */
(function (global) {
  "use strict";

  const WIZARDS = [
    {
      id: "ember",
      name: "Ember",
      emoji: "🔥",
      school: "fire",
      tag: "Fire · Fast",
      desc: "Rapid fireballs. Hits chip the wall hard.",
      color: "#ff6b3d",
      color2: "#ffb347",
      spell: "fireball",
      speed: 1.35,
      damage: 12,
      cooldown: 0.22,
      size: 11,
      special: "burn", // wall DOT after hit
    },
    {
      id: "frost",
      name: "Frost",
      emoji: "❄️",
      school: "ice",
      tag: "Ice · Slow",
      desc: "Chill orbs. Blocks freeze the paddle briefly.",
      color: "#6ecbff",
      color2: "#b8ecff",
      spell: "iceorb",
      speed: 0.95,
      damage: 10,
      cooldown: 0.28,
      size: 13,
      special: "slow",
    },
    {
      id: "shade",
      name: "Shade",
      emoji: "🌑",
      school: "shadow",
      tag: "Shadow · Decoy",
      desc: "Launches a real bolt plus a fake decoy.",
      color: "#b56bff",
      color2: "#6b3cff",
      spell: "shadow",
      speed: 1.12,
      damage: 11,
      cooldown: 0.32,
      size: 10,
      special: "decoy",
    },
    {
      id: "volt",
      name: "Volt",
      emoji: "⚡",
      school: "volt",
      tag: "Lightning · Laser",
      desc: "Piercing lasers. Extra edge rebounds.",
      color: "#ffe566",
      color2: "#fff4b0",
      spell: "laser",
      speed: 1.55,
      damage: 9,
      cooldown: 0.24,
      size: 7,
      special: "pierce",
      maxBounces: 6,
    },
    {
      id: "venom",
      name: "Venom",
      emoji: "🐍",
      school: "venom",
      tag: "Nature · Split",
      desc: "Toxic bolts that split on wall bounce.",
      color: "#5dff9a",
      color2: "#b8ffd4",
      spell: "venom",
      speed: 1.08,
      damage: 8,
      cooldown: 0.28,
      size: 10,
      special: "split",
    },
    {
      id: "arcane",
      name: "Arcane",
      emoji: "✨",
      school: "arcane",
      tag: "Arcane · Heavy",
      desc: "Slow meteor orbs. Massive wall damage.",
      color: "#ff6ad5",
      color2: "#ffb0ec",
      spell: "meteor",
      speed: 0.82,
      damage: 18,
      cooldown: 0.4,
      size: 16,
      special: "heavy",
    },
  ];

  const DEFENDERS = [
    {
      id: "knight",
      name: "Iron Knight",
      emoji: "🛡️",
      school: "knight",
      tag: "Sturdy",
      desc: "Wide base shield. Growth/shrink dampened.",
      color: "#c0c8d8",
      color2: "#6a7388",
      baseWidth: 1.15,
      speed: 1.0,
      growMod: 0.85,
      shrinkMod: 0.85,
      wallResist: 1.0,
      special: null,
    },
    {
      id: "dragon",
      name: "Red Dragon",
      emoji: "🐉",
      school: "dragon",
      tag: "Fire Breath",
      desc: "Double-tap to breathe fire and burn spells.",
      color: "#ff6b3d",
      color2: "#8b1a1a",
      baseWidth: 1.0,
      speed: 0.95,
      growMod: 1.0,
      shrinkMod: 1.0,
      wallResist: 1.0,
      special: "breath",
      breathCd: 4.5,
    },
    {
      id: "king",
      name: "Castle King",
      emoji: "👑",
      school: "king",
      tag: "Royal Guards",
      desc: "Spawns side guards every few blocks.",
      color: "#ffd56a",
      color2: "#c48a20",
      baseWidth: 1.0,
      speed: 0.9,
      growMod: 1.0,
      shrinkMod: 1.0,
      wallResist: 0.9,
      special: "guards",
    },
    {
      id: "ranger",
      name: "Swift Ranger",
      emoji: "🏹",
      school: "ranger",
      tag: "Agile",
      desc: "Lightning-fast paddle. Slimmer base.",
      color: "#5dff9a",
      color2: "#1a6b40",
      baseWidth: 0.88,
      speed: 1.45,
      growMod: 1.1,
      shrinkMod: 1.05,
      wallResist: 1.05,
      special: null,
    },
    {
      id: "golem",
      name: "Stone Golem",
      emoji: "🗿",
      school: "golem",
      tag: "Fortress",
      desc: "Wall takes far less damage. Heavy paddle.",
      color: "#b8a090",
      color2: "#5a4a3a",
      baseWidth: 1.2,
      speed: 0.75,
      growMod: 0.9,
      shrinkMod: 0.75,
      wallResist: 0.55,
      special: null,
    },
    {
      id: "witch",
      name: "Hex Witch",
      emoji: "🧙‍♀️",
      school: "witch",
      tag: "Nullify",
      desc: "Chance to erase spell specials on block.",
      color: "#b56bff",
      color2: "#3a1a6a",
      baseWidth: 1.0,
      speed: 1.05,
      growMod: 1.0,
      shrinkMod: 1.0,
      wallResist: 1.0,
      special: "nullify",
      nullifyChance: 0.4,
    },
  ];

  const POWERUPS = [
    { id: "multi", name: "Triple Cast", emoji: "🔱", color: "#ff6ad5", duration: 0, apply: "multi" },
    { id: "giant", name: "Giant Shield", emoji: "🛡️", color: "#ffd56a", duration: 6, apply: "giant" },
    { id: "freeze", name: "Time Freeze", emoji: "🧊", color: "#6ecbff", duration: 2.2, apply: "freeze" },
    { id: "repair", name: "Stone Mend", emoji: "🧱", color: "#5dff9a", duration: 0, apply: "repair" },
    { id: "haste", name: "Haste Sigil", emoji: "💨", color: "#ffe566", duration: 5, apply: "haste" },
    { id: "magnet", name: "Magnet Aegis", emoji: "🧲", color: "#b56bff", duration: 5, apply: "magnet" },
  ];

  const CFG = {
    WALL_MAX: 100,
    BASE_PADDLE_W: 78,
    PADDLE_H: 16,
    PADDLE_MIN_SCALE: 0.45,
    PADDLE_MAX_SCALE: 2.2,
    GROW: 0.1,
    SHRINK: 0.1,
    ROUND_TIME: 120, // seconds per round (duel)
    BEST_OF: 3,
    CASTLE_Y_RATIO: 0.92,
    PADDLE_Y_RATIO: 0.84,
    WIZARD_ZONE: 0.18,
    FIELD_TOP: 0.2,
    FIELD_BOT: 0.82,
    POWERUP_CHANCE: 0.18,
    POWERUP_INTERVAL: 7,
    ENDLESS_SPAWN_SCALE: 0.012,
  };

  global.TT = global.TT || {};
  global.TT.WIZARDS = WIZARDS;
  global.TT.DEFENDERS = DEFENDERS;
  global.TT.POWERUPS = POWERUPS;
  global.TT.CFG = CFG;
})(typeof window !== "undefined" ? window : globalThis);
